name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # или ваша версия Python
          
      - name: Install dependencies
        run: |
          pip install -r ms-bfs/requirements.txt
          
      - name: Run GraphBMS MS_BFS
        working-directory: ./ms-bfs/graphblas
        run: python MS_BFS.py
        
      - name: Run PySpark MS_BFS
        working-directory: ./ms-bfs/pyspark
        run: python MS_BFS.py